[project]
name = "raft-kv"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
  "httpx>=0.27",
  "pydantic>=2.7",
  "pyyaml>=6.0.1",
  "aiofiles>=23.2",
]

[tool.uvicorn]
factory = true
