node_id: n1
host: 127.0.0.1
port: 7101
data_dir: .data/n1
election_timeout_ms_min: 3000
election_timeout_ms_max: 5000
heartbeat_ms: 10
peers:
  - { id: n2, url: "http://127.0.0.1:7102" }
  - { id: n3, url: "http://127.0.0.1:7103" }
