node_id: n2
host: 127.0.0.1
port: 7102
data_dir: .data/n2
election_timeout_ms_min: 2000
election_timeout_ms_max: 3000
heartbeat_ms: 1000
peers:
  - { id: n1, url: "http://127.0.0.1:7101" }
  - { id: n3, url: "http://127.0.0.1:7103" }
