node_id: n3
host: 127.0.0.1
port: 7103
data_dir: .data/n3
election_timeout_ms_min: 3000
election_timeout_ms_max: 5000
heartbeat_ms: 10
peers:
  - { id: n1, url: "http://127.0.0.1:7101" }
  - { id: n2, url: "http://127.0.0.1:7102" }
